# Generated by Django 2.2.16 on 2022-10-22 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postslikes',
            name='like',
        ),
        migrations.AlterField(
            model_name='postslikes',
            name='liked_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='like_by', to=settings.AUTH_USER_MODEL, verbose_name='Поставил лайк'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postslikes',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='likes', to='posts.Post', verbose_name='Пост'),
            preserve_default=False,
        ),
    ]
