# Generated by Django 2.2.19 on 2023-03-09 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=200,
                     verbose_name='Заголовок')),
                ('slug',
                 models.SlugField(
                     unique=True,
                     verbose_name='Адрес страницы с группой')),
                ('description',
                 models.TextField(
                     verbose_name='Описание группы')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='Дата создания')),
                ('text',
                 models.TextField(
                     help_text='Введите текст',
                     verbose_name='Текст поста')),
                ('image',
                 models.ImageField(
                     blank=True,
                     upload_to='posts/',
                     verbose_name='Картинка')),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='posts',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Автор')),
                ('group',
                 models.ForeignKey(
                     blank=True,
                     help_text='Группа, к которой будет относиться пост',
                     null=True,
                     on_delete=django.db.models.deletion.SET_NULL,
                     related_name='posts',
                     to='posts.Group',
                     verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': (
                    '-created',
                ),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True,
                     verbose_name='Дата создания')),
                ('text',
                 models.TextField(
                     help_text='Введите комментарий',
                     verbose_name='Текст комментария')),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comments',
                     to=settings.AUTH_USER_MODEL,
                     verbose_name='Автор')),
                ('post',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='comments',
                     to='posts.Post',
                     verbose_name='Пост')),
            ],
            options={
                'ordering': (
                    '-created',
                ),
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('author',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='following',
                     to=settings.AUTH_USER_MODEL)),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     related_name='follower',
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {
                    (
                        'user',
                        'author')},
            },
        ),
    ]
