# Generated by Django 2.2.16 on 2022-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20221014_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': (
                '-pub_date',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True, upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
