# Generated by Django 2.2.16 on 2022-10-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20221014_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='comments', to='posts.Post', verbose_name='Пост'),
        ),
    ]
