# Generated by Django 2.2.16 on 2022-10-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_follow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='current_user',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='follow',
            name='post_author',
            field=models.IntegerField(default=None),
        ),
    ]
