# Generated by Django 2.2.16 on 2022-10-17 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0013_auto_20221017_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='current_user',
        ),
        migrations.AddField(
            model_name='follow',
            name='currnet_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='follower', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='follow',
            name='post_author',
        ),
        migrations.AddField(
            model_name='follow',
            name='post_author',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
